version: "2.3"
services:
  # Service is based on https://github.com/xingyizhou/CenterTrack/pull/176
  dev:
    image: deft_dev
    build:
      context: .
    tty: true
    ipc: host
    runtime: nvidia
    ports:
      - "${NOVNC_PORT}:80"
      - "${VNC_PORT}:5900"
      - "${CODE_SERVER_PORT}:8080"
    hostname: "${COMPOSE_PROJECT_NAME}_dev_${HOST}"
    volumes:
      - .:/project
      - /home/shared/planning-research/data:/project/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PASSWORD=${PASSWORD}
      - VNC_PASSWORD=${VNC_PASSWORD}
